name: tdmb2
version: 2.4.0
description: TDMB (Teknik Dasar Mesatua Bali)
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cupertino_icons: any
  get: ^4.3.8
  flutter_launcher_name: any
  #  flutter_launcher_icons: any
  carousel_slider: any
  modal_bottom_sheet: 2.0.0
  http: 0.13.4
  url_launcher: ^6.0.10
  intl: 0.17.0
  pinch_zoom: ^1.0.0
  mailto: any
  native_shared_preferences: any
  top_snackbar_flutter: 1.0.0
  get_storage: 2.0.3
  package_info: any
  firebase_messaging: ^10.0.8
  flutter_html: any
  share: 2.0.4
  pdf_viewer_plugin: 2.0.1
  random_string: any
  wakelock: ^0.6.2
  file_picker: any
  change_app_package_name: 1.0.0
  firebase_analytics: 8.3.3
  firebase_core: 1.7.0
  intl_phone_field: 2.1.0
  intl_phone_number_input: 0.7.0+2
  firebase_auth: 3.1.3
  font_awesome_flutter: 9.1.0
  flutter_signin_button: 2.0.0
  google_sign_in: 5.1.1
  lottie: any
  flutter_datetime_picker: 1.5.1
  fluttericon: 2.0.0
  shirne_dialog: 1.6.0
  easy_debounce: 2.0.1
  syncfusion_flutter_barcodes: 19.3.55
  confirm_dialog: 1.0.0
  animate_do: 2.0.0
  video_player: 2.4.7
  assets_audio_player: any
  chewie: 1.5.0
  alert: 2.0.1
  image_picker: 0.8.4+4
  flutter:
    sdk: flutter
  audiofileplayer: ^2.1.1
  ocarina: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: launcher_icon
  image_path_android: assets/images/icon.png
  image_path_ios: assets/images/icon.png
  ios: true

flutter_launcher_name:
  name: TDMB (Teknik Dasar Mesatua Bali)

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/animasi/
    - assets/audio/
    - assets/video/
  fonts:
    - family: italic
      fonts:
        - asset: fonts/Poppins-Italic.ttf
    - family: regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: bold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
  uses-material-design: true

